services:
  - type: web
    name: natures-uplift
    env: python
    region: oregon

    buildCommand: "pip install -r requirements.txt"

    startCommand: >
      python manage.py migrate --noinput &&
      gunicorn natures_uplift.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

      - key: DJANGO_SETTINGS_MODULE
        value: natures_uplift.settings

      - key: SECRET_KEY
        generateValue: true


