services:
  - type: web
    name: natures-uplift
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn natures_uplift.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: natures_uplift.settings
    preDeployCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
