services:
  - type: web
    name: natures-uplift
    env: python
    region: oregon

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn natures_uplift.wsgi:application

    postDeploy:
      - python manage.py migrate --noinput

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: natures_uplift.settings

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: natureupliftdb
          property: connectionString

databases:
  - name: natureupliftdb
    region: oregon
